### ISSUE TITLE
Support table joins in FFI

### ISSUE THREAD

**Issue by WebFreak001** [myOmikron/drorm#21]
currently my implementation is waiting for the FFI side for joins (introduced in https://github.com/myOmikron/drorm/commit/cb5e8682ae21741dbf8aa63aa0f9ba28ed3c406b)

My API suggestion: https://github.com/myOmikron/drorm/blob/9772f48d9f9fa22301bf459cf5228cf80e74bb3f/dorm/source/dorm/lib/ffi.d#L1084-L1095 + adding an `FFISlice!FFIJoin` parameter for rorm_db_query_all, rorm_db_query_one and rorm_db_query_stream

**Comment by myOmikron** [comment]
Closed by 62cc8070c33700dfce5fe82ad4cdcf0eedb270e7.
